import argparse
import json
import os
from decision_engine.input_layer.schemas import UnvalidatedArchitectureHypothesis
from idea_refiner.orchestrator import Orchestrator
from idea_refiner.parsers.base import BaseIdeaParser
from decision_engine.tree.context import DecisionContext
from decision_engine.tree.optimizer import optimize_tree
from idea_refiner.parsers.epistemic_resolver import EpistemicResolution
from decision_engine.tree.epistemic import EpistemicValidator
from decision_engine.tree.tree_schemas import PathNode

class PassthroughParser(BaseIdeaParser):
    def __init__(self, hypotheses):
        self.hypotheses = hypotheses
        
    def parse_idea_to_graph(self, idea: str):
        return self.hypotheses

def main():
    parser = argparse.ArgumentParser(description="Idea Refiner Engine CLI")
    parser.add_argument("--proposals", type=str, help="Path to UNTRUSTED proposals JSON generated by the agent")
    parser.add_argument("--resolution", type=str, help="Path to UNTRUSTED epistemic resolution JSON generated by the agent")
    parser.add_argument("--state", type=str, default="session/graph_state.json", help="Path to the ENGINE-OWNED state file")
    
    args = parser.parse_args()
    
    if not args.proposals and not args.resolution:
        print("Must provide either --proposals or --resolution")
        return
        
    os.makedirs(os.path.dirname(args.state), exist_ok=True)
    
    context = DecisionContext(
        ontology_version="v1",
        registry_policy_hashes=[],
        environment_constraints=["network: offline"],
        optimizer_preferences={"cost_lambda": 0.5, "epistemic_lambda": 1.0, "complexity_lambda": 0.1, "robustness_lambda": 0.0}
    )
    
    decision_graph = []
    
    # Load previous engine-owned state if it exists
    if os.path.exists(args.state):
        with open(args.state, "r") as f:
            state_data = json.load(f)
            # Deserialize PathNodes
            decision_graph = [PathNode.model_validate(node_dict) for node_dict in state_data]

    if args.proposals:
        with open(args.proposals, "r") as f:
            raw_proposals = json.load(f)
        
        # Deserialize untrusted proposals
        hypotheses = [UnvalidatedArchitectureHypothesis.model_validate(h) for h in raw_proposals]
        
        # Route directly to engine boundary (bypassing any orchestration layer)
        from decision_engine.input_layer.schemas import ArchitectureNode
        from decision_engine.tree.optimizer import create_evaluated_path_node
        
        for i, hyp in enumerate(hypotheses):
            arch = ArchitectureNode(
                inputs=getattr(hyp, 'inputs', []),
                processing=getattr(hyp, 'processing', []),
                decision=getattr(hyp, 'decision', []),
                output=getattr(hyp, 'output', []),
                capabilities=getattr(hyp, 'capabilities', []),
                semantic_dependencies=getattr(hyp, 'semantic_dependencies', []),
                data_required=getattr(hyp, 'data_required', []),
                resources_required=getattr(hyp, 'resources_required', []),
                constraints=getattr(hyp, 'constraints', []),
                architectural_decisions=getattr(hyp, 'architectural_decisions', {})
            )
            node = create_evaluated_path_node(
                arch=arch,
                context=context,
                node_id=getattr(hyp, 'id', None) or f"cand_{i}",
                parent_id=getattr(hyp, 'parent_id', None) or "root",
                provenance=getattr(hyp, 'provenance', None),
                operational_complexity=getattr(hyp, 'operational_complexity', 0.0)
            )
            decision_graph.append(node)
            
    if args.resolution:
        with open(args.resolution, "r") as f:
            raw_resolution = json.load(f)
            
        # Deserialize untrusted resolution
        resolution = EpistemicResolution.model_validate(raw_resolution)
        
        updated_graph = []
        for node in decision_graph:
            # Route to engine validation boundary
            is_valid, new_node = EpistemicValidator.validate_and_apply(
                resolution, node, target_uncertainty=resolution.target
            )
            if is_valid and new_node:
                # Engine recalculates status based on new epistemic state
                if new_node.status != "REJECTED":
                    # Simple re-evaluation for proof purposes
                    new_node.status = "TERMINAL" if "basic_mobile_hardware" in new_node.architecture.semantic_dependencies else "UNRESOLVED"
                updated_graph.append(new_node)
            else:
                updated_graph.append(node)
        decision_graph = updated_graph
        
    # Serialize and save ENGINE-OWNED state
    with open(args.state, "w") as f:
        json.dump([node.model_dump() for node in decision_graph], f, indent=2)
        
    # Engine computes Argmax
    result = optimize_tree(decision_graph, context)
    
    # Output the Tamper-Evident Trace
    print("=== ENGINE OPTIMIZATION RESULT ===")
    print(f"Decision Fingerprint: {result.decision_fingerprint}")
    print(f"Winning Node ID:      {result.best_path_id}")
    print(f"Effective Score:      {result.effective_score}")
    print("==================================")
    
if __name__ == "__main__":
    main()
