from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from enum import Enum

class Winner(str, Enum):
    USER = "user"
    PLAYER_B = "player_b"
    TIE = "tie"

class CandidateStatus(str, Enum):
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    NO_CANDIDATE = "NO_CANDIDATE"

class EvalStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"

class Requirement(BaseModel):
    name: str
    required: bool

class RequirementEvaluation(BaseModel):
    requirement: str
    user_satisfies: bool
    player_b_satisfies: bool
    user_reason: str
    player_b_reason: str

class HistoricalEvidence(BaseModel):
    source_project: str
    evidence_pattern: str
    why_it_worked: str
    applicability: str

class TransferredDecision(BaseModel):
    historical_decision: str
    historical_evidence: HistoricalEvidence
    decision_status: str
    reasoning: str

class UnvalidatedArchitectureHypothesis(BaseModel):
    """
    Represents an architecture hypothesis generated by an LLM or external source.
    This is intentionally NOT an ArchitectureNode, enforcing the semantic boundary 
    that it is unvalidated and lacks authority.
    """
    inputs: List[str] = []
    processing: List[str] = []
    decision: List[str] = []
    output: List[str] = []
    
    capabilities: List[str] = []
    semantic_dependencies: List[str] = []
    data_required: List[str] = []
    resources_required: List[str] = []
    constraints: List[str] = []
    architectural_decisions: Dict[str, str] = {}
    
    id: str = ""
    parent_id: Optional[str] = None
    generation_reason: Optional[str] = None
    source: str = "llm_generated"
    hypothesis: bool = True
    provenance: Dict[str, Any] = {}

    def get_signature(self) -> str:
        """
        Returns a canonical signature to test diversity of hypotheses.
        """
        import hashlib
        import json
        canonical_dict = {
            "inputs": sorted(self.inputs),
            "processing": sorted(self.processing),
            "decision": sorted(self.decision),
            "output": sorted(self.output),
            "capabilities": sorted(self.capabilities),
            "semantic_dependencies": sorted(self.semantic_dependencies),
            "data_required": sorted(self.data_required),
            "resources_required": sorted(self.resources_required),
            "constraints": sorted(self.constraints),
            "architectural_decisions": {k: self.architectural_decisions[k] for k in sorted(self.architectural_decisions.keys())}
        }
        canonical_json = json.dumps(canonical_dict, sort_keys=True)
        return hashlib.sha256(canonical_json.encode('utf-8')).hexdigest()

class ArchitectureNode(BaseModel):
    inputs: List[str] = []
    processing: List[str] = []
    decision: List[str] = []
    output: List[str] = []
    
    capabilities: List[str] = []
    semantic_dependencies: List[str] = []
    data_required: List[str] = []
    resources_required: List[str] = []
    constraints: List[str] = []
    evidence_provenance: List[str] = []
    historical_decisions: List[TransferredDecision] = []
    architectural_decisions: Dict[str, str] = {}

    candidate_status: Optional[CandidateStatus] = CandidateStatus.FEASIBLE
    performance: Optional[Dict[str, Any]] = None
    cost: Optional[Dict[str, Any]] = None
    timeline: Optional[Dict[str, Any]] = None

    def get_fingerprint(self) -> str:
        """
        Returns a canonical SHA256 fingerprint of the architecture.
        This provides a deterministic tie-breaker for optimization.
        """
        import hashlib
        import json
        
        canonical_dict = {
            "inputs": sorted(self.inputs),
            "processing": sorted(self.processing),
            "decision": sorted(self.decision),
            "output": sorted(self.output),
            "capabilities": sorted(self.capabilities),
            "semantic_dependencies": sorted(self.semantic_dependencies),
            "data_required": sorted(self.data_required),
            "resources_required": sorted(self.resources_required),
            "constraints": sorted(self.constraints),
            "architectural_decisions": {k: self.architectural_decisions[k] for k in sorted(self.architectural_decisions.keys())}
        }
        
        canonical_json = json.dumps(canonical_dict, sort_keys=True)
        return hashlib.sha256(canonical_json.encode('utf-8')).hexdigest()

class UserIdea(BaseModel):
    what: str
    why: str
    how_raw: str
    how_structured: ArchitectureNode

class ProjectProfile(BaseModel):
    domains: List[str]
    problem_types: List[str]
    solution_types: List[str]
    primary_values: List[str]
    user_types: List[str]
    constraints: List[str]

class DecisionEvidence(BaseModel):
    decision: str
    source_project: str
    supporting_pattern: str
    evidence: str

class CandidateApproach(BaseModel):
    name: str
    description: str
    evidence: List[DecisionEvidence]

class DimensionEvaluation(BaseModel):
    constraint: EvalStatus = EvalStatus.UNKNOWN
    requirement: EvalStatus = EvalStatus.UNKNOWN
    performance: EvalStatus = EvalStatus.UNKNOWN
    cost: EvalStatus = EvalStatus.UNKNOWN
    timeline: EvalStatus = EvalStatus.UNKNOWN

class ArchitectureComparison(BaseModel):
    b_feasible: bool = False
    a_feasible: bool = False
    b_reqs_satisfied: bool = False
    a_reqs_satisfied: bool = False
    
    b_constraint_violations: List[str] = []
    a_constraint_violations: List[str] = []
    
    requirement_evaluations: List[RequirementEvaluation] = []
    
    b_dimensions: DimensionEvaluation = Field(default_factory=DimensionEvaluation)
    a_dimensions: DimensionEvaluation = Field(default_factory=DimensionEvaluation)

    winner: Winner
    reasoning: str

class PlayerBResponse(BaseModel):
    candidate_approaches: List[CandidateApproach]
    player_b_architecture: ArchitectureNode
    evidence: List[DecisionEvidence]
